### ISSUE TITLE
support TCP sockets

### ISSUE THREAD

**Issue by nicojanssens** [MicroMinion/turn-js#2]

**Comment by 161chihuahuas** [comment]
:+1: happy to help with this too, so kad-traverse works with more transports!

**Comment by nicojanssens** [comment]
Transport branch includes updated version of turn-js client, which can use both UDP and TCP sockets. Will merge once docs are ready + integrate in kad-traverse lib of @gordonwritescode

**Comment by 161chihuahuas** [comment]
Nice! :+1:
